### ISSUE TITLE
Azure-login script fails

### ISSUE THREAD

**Issue by cwelton** [weaveworks-guides/weave-kubernetes-coreos-azure#6]
Following the instructions yields the following error.

```
bash$ azure login
info:    Executing command login
/info:    To sign in, use a web browser to open the page https://aka.ms/devicelogin. Enter the code xxxxxxx to authenticate.
|info:    Added subscription Free Trial
+
info:    login command OK

bash$ ./azure-login.js
buffer.js:70
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:70:13)
    at Interactor.initProgressBars (/Users/cwelton/projects/weave-kubernetes-coreos-azure/node_modules/azure-cli/lib/util/interaction.js:41:24)
    at new Interactor (/Users/cwelton/projects/weave-kubernetes-coreos-azure/node_modules/azure-cli/lib/util/interaction.js:32:8)
    at new AzureCli (/Users/cwelton/projects/weave-kubernetes-coreos-azure/node_modules/azure-cli/lib/cli.js:43:22)
    at /Users/cwelton/projects/weave-kubernetes-coreos-azure/node_modules/azure-cli/bin/azure.js:35:11
    at Object.exports.isTelemetryEnabled (/Users/cwelton/projects/weave-kubernetes-coreos-azure/node_modules/azure-cli/lib/util/utilsCore.js:181:12)
    at Object.<anonymous> (/Users/cwelton/projects/weave-kubernetes-coreos-azure/node_modules/azure-cli/bin/azure.js:27:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

Same error is raised if I assume that a basic `azure login` is sufficient and try to proceed on to the `create-kubernetes-cluster.js` script.

**Comment by cwelton** [comment]
```
bash$ npm version
{ 'coreos-azure-weave': '1.0.0',
  npm: '3.10.7',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.6.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.1.281.83',
  zlib: '1.2.8' }
```

**Comment by jordanyaker** [comment]
@cwelton this is a Node 6.x error.  If you use Node 5.x this goes away.

**Comment by marty2bell** [comment]
Hi

Is there a fix for the script that makes it compatible with node 6.x.  Seems wrong do downgrade the version of node?

Many Thanks

Marty

**Comment by jdumars** [comment]
It's not just a node 6.x issue:
```
[root@ip-172-31-57-31 weave-kubernetes-coreos-azure]# ./azure-login.js -u user@whytrumpomfg.com
buffer.js:89
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:89:13)
    at Interactor.initProgressBars (/home/ec2-user/repos/weave-kubernetes-coreos-azure/node_modules/azure-cli/lib/util/interaction.js:41:24)
    at new Interactor (/home/ec2-user/repos/weave-kubernetes-coreos-azure/node_modules/azure-cli/lib/util/interaction.js:32:8)
    at new AzureCli (/home/ec2-user/repos/weave-kubernetes-coreos-azure/node_modules/azure-cli/lib/cli.js:43:22)
    at /home/ec2-user/repos/weave-kubernetes-coreos-azure/node_modules/azure-cli/bin/azure.js:35:11
    at Object.exports.isTelemetryEnabled (/home/ec2-user/repos/weave-kubernetes-coreos-azure/node_modules/azure-cli/lib/util/utilsCore.js:181:12)
    at Object.<anonymous> (/home/ec2-user/repos/weave-kubernetes-coreos-azure/node_modules/azure-cli/bin/azure.js:27:11)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
```
Versions:
```
[root@ip-172-31-22-22 weave-kubernetes-coreos-azure]# npm version
{ 'coreos-azure-weave': '1.0.0',
  npm: '3.10.9',
  ares: '1.10.1-DEV',
  cldr: '29.0',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '51',
  node: '7.1.0',
  openssl: '1.0.2j',
  tz: '2016b',
  unicode: '8.0',
  uv: '1.10.0',
  v8: '5.4.500.36',
  zlib: '1.2.8' }

[root@ip-172-31-22-22 weave-kubernetes-coreos-azure]# azure --version
0.10.7 (node: 7.1.0)
```

**Comment by cooktheryan** [comment]
I did a work around by using 
azure login

**Comment by kidk** [comment]
@cooktheryan Were you able to run ./create-kubernetes-cluster.js?

It gives me the same error.

**Comment by cooktheryan** [comment]
weird switching to azure login rather than running /azure-login.js worked when i had attempted it

**Comment by errordeveloper** [comment]
I am closing this issue as I am going to archive this repo.
